#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u MNetV2.py "$@"

# The previous version of this file was commented-out and follows below:
#
# python -u FC_with_inceptionv3_MNet.py "$@"
# 
# # The previous version of this file was commented-out and follows below:
# #
# # python -u FC_with_inceptionv3_MNet.py "$@"
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # python -u FC_with_inceptionv3_TL.py "$@"
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
# # # # python -u FC_with_inceptionv3_TL.py "$@"
# # # # 
# # # # # The previous version of this file was commented-out and follows below:
# # # # #
# # # # # python -u FC_with_inceptionv3_plainModel.py "$@"
# # # # # 
# # # # # # The previous version of this file was commented-out and follows below:
# # # # # #
# # # # # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'FruiClassification_with_inceptionv3_plainModel'."
# # # # # # 
# # # # # 
# # # # 
# # # 
# # 
# 
